### ISSUE TITLE
hg link not available

### ISSUE THREAD

**Issue by leeyoyohku** [oaxiom/glbase3#2]
Hi glbase development team,

I found glbase3 very useful when doing RNA-seq analysis last year. As I just wanted to use it, however, it seems the hg clone link doesn't exit, seen as below:
`$ hg clone --debug https://bitbucket.org/oaxiom/glbase2using https://bitbucket.org/oaxiom/glbase2
sending capabilities command
abort: HTTP Error 404: Not Found`

Could you provide any solution to this?

Your help will be appreciated.

**Comment by oaxiom** [comment]
That's right, the mercurial clone is broken as bitbucket no longer supports hg. I ported glbase3 to git, to fix, just reclone from the github repository:

git clone https://github.com/oaxiom/glbase3.git

**Comment by oaxiom** [comment]
Then git pull as needed.

**Comment by leeyoyohku** [comment]
Thank @oaxiom a lot for your reply
