### ISSUE TITLE
professor, you can use requirements.txt to help other people install the package they need with right version

### ISSUE THREAD

**Issue by yuegew** [oaxiom/glbase3#3]
To create requirements.txt， simply type `**$ pip freeze >requirements.txt**`
To use the requirements.txt, simply  type `**$ pip install -r requirements.txt**`
[python笔记---需求文件requirements.txt的创建及使用](https://blog.csdn.net/loyachen/article/details/52028825)

**Comment by oaxiom** [comment]
Cool. I didn't know about this feature, although it seems to just grab all the python modules I have installed, rather than those really required. Still, some may find it useful for the dependency problems, so I added and committed.
